# Makefile for the p2 assignment
# Name: Ethan Hess
# Section: 3060-x02

CC=gcc
CFLAGS=-Wall -g
TARGET=p2
SRC=p2.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
